name: Docker Build
run-name: ${{ github.actor }} triggers Docker Build from tag ${{ github.ref_name }}

on:
  push:
    tags:
      - v**

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn   # do NOT cache the node_modules folder though
          cache-dependency-path: app/yarn.lock
      - name: Installing dependencies
        run: yarn install --frozen-lockfile   # optional: --immutable to abort if the lockfile was to be modified

  test:
    name: Test
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn   # do NOT cache the node_modules folder though
          cache-dependency-path: app/yarn.lock
      - name: Testing App
        run: yarn test

#   build:
#     name: Build
#     # needs: Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
# #     - name: Set up Docker Buildx
# #       uses: docker/setup-buildx-action@v2
# #     - name: Build
# #       uses: docker/build-push-action@v3
# #       with:
# #         push: false
